all:
	@echo
	@echo "<<<<<<<<<< Python code start: >>>>>>>>>>"
	@echo
	@python3 Solution.py
	@echo
	@echo "<<<<<<<<<<< Python code end. >>>>>>>>>>"
	@echo
	@echo "========== Swift code start: =========="
	@echo
	@swift Solution.swift
	@echo
	@echo "=========== Swift code end. =========="
